apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
  labels:
    environment: {{ .Release.Namespace }}
    app: {{ .Values.global.product }}
    tier: {{ .Values.appName}}
spec:
  ports:
    - port: 5432
  selector:
    app: {{ .Values.global.product }}
    tier: {{ .Values.appName }}
