dependencies:
  - name: redis
    version: 0.1.0
    condition: global.redis.internal

  - name: elasticsearch
    version: 0.1.0
    condition: global.elasticsearch.internal

  - name: rabbitmq-ha
    version: 0.1.0
    condition: global.mq.internal

  - name: nginx-ingress
    version: 0.1.0
    condition: global.ingress.internal
