{{- if and (eq .Values.global.ingress.class "aws-dual") (not .Values.global.ingress.internal) }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.appName }}-{{ .Release.Namespace }}-internal
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/certificate-arn: {{ .Values.global.alb.certificatearn }}
    alb.ingress.kubernetes.io/healthcheck-path: /ping
    alb.ingress.kubernetes.io/success-codes: '200'
    alb.ingress.kubernetes.io/scheme: internal
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.global.subdomain }}.{{ .Values.global.domain }}
  labels:
    environment: {{ .Release.Namespace }}
    app: {{ .Values.global.product }}
    tier: {{ .Values.appName }}
spec:
  rules:
    - host: {{ .Values.global.subdomain}}.{{ .Values.global.domain }}
      http:
        paths:
          - backend:
              serviceName: corezoid-web-adm
              servicePort: 80
    - host: superadm-{{ .Values.global.subdomain}}.{{ .Values.global.domain }}
      http:
        paths:
          - backend:
              serviceName: corezoid-web-superadm
              servicePort: 80
    - host: {{ .Values.global.syncapi.subdomain}}.{{ .Values.global.domain }}
      http:
        paths:
          - backend:
              serviceName: syncapi-web
              servicePort: 80
{{- end }}
