apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-service
  labels:
    app: {{ .Values.global.product }}
    tier: {{ .Values.appName }}
spec:
  selector:
    app: {{ .Values.global.product }}
    tier: {{ .Values.appName }}
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090
  clusterIP: None
