apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-service
  labels:
    environment: {{ .Release.Namespace }}
    app: {{ .Values.global.product }}
    tier: {{ .Values.appName }}
spec:
  selector:
    environment: {{ .Release.Namespace }}
    app: {{ .Values.global.product }}
    tier: {{ .Values.appName }}
  ports:
  - protocol: TCP
    name: main
    port: {{ .Values.containers.containerPort }}
    targetPort: {{ .Values.containers.containerPort }}
  - protocol: TCP
    name: managment
    port: 7980
    targetPort: 7980